version: '3'

services:
  db:
    image: postgres
    container_name: postgres-brain-ag
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "brain-ag-db"
    ports:
      - "5432:5432"